version: '3.8'
services:
    mongo1:
        build: .
        image: mongocustom:8.0.1
        container_name: mongo1
        hostname: mongo1
        networks:
            - mongonet
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=adminpassword
            - MONGO_INITDB_DATABASE=test
        command: --config /etc/mongod.conf --port 27017


        healthcheck:
            test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 2s
            retries: 5

    mongo2:
        build: .
        image: mongocustom:8.0.1
        container_name: mongo2
        hostname: mongo2
        networks:
            - mongonet
        ports:
            - "27018:27018"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=adminpassword
            - MONGO_INITDB_DATABASE=test
        command: --config /etc/mongod.conf --port 27018


        healthcheck:
            test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 2s
            retries: 5

    mongo3:
        build: .
        image: mongocustom:8.0.1
        container_name: mongo3
        hostname: mongo3
        networks:
            - mongonet
        ports:
            - "27019:27019"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=adminpassword
            - MONGO_INITDB_DATABASE=test
        command: --config /etc/mongod.conf --port 27019


        healthcheck:
            test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 2s
            retries: 5

    mongodb_setup:
        build: .
        image: mongocustom:8.0.1
        hostname: mongodb_setup
        container_name: mongodb_setup
        networks:
            - mongonet
        depends_on:
            mongo1:
                condition: service_healthy
            mongo2:
                condition: service_healthy
            mongo3:
                condition: service_healthy

        command: >
            mongosh --host mongo1:27017 --username admin --password adminpassword --authenticationDatabase admin --eval
            '
            rs.initiate(
              {
                _id: "replica_set_single",
                version: 1,
                members: [
                    { _id: 0, host : "mongo1:27017"},
                    { _id: 1, host : "mongo2:27018"},
                    { _id: 2, host : "mongo3:27019"}
                ]
              }
            );
            '
    redis-stack:
        image: redis/redis-stack:latest
        volumes:
            - redis-stack-data:/bitnami/redis/data
        ports:
            - "8001:8001"
            - "6379:6379"
        networks:
            - redisnet

    zookeeper:
        image: zookeeper:latest
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_SERVER_ID: 1
            #ZOOKEEPER_SERVERS: zookeeper:2888:3888
            ZOOKEEPER_TICK_TIME: 2000

        networks:
            - kafkanet

        healthcheck:
            test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
            interval: 10s
            timeout: 5s
            retries: 3

    kafka1:
        image: bitnami/kafka:latest
        hostname: kafka1
        container_name: kafka1
        ports:
            - "9092:9092"
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:9092,DOCKER://:29092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092,DOCKER://kafka1:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LOG4J_LOGGERS: "kafka.controller=DEBUG,kafka.producer.async.DefaultEventHandler=DEBUG,state.change.logger=DEBUG"
            #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            #KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

        depends_on:
            zookeeper:
                condition: service_healthy

        #command: ["sh", "-c", "sleep 15; kafka-topics.sh --create --topic rents --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092 && sleep infinity"]

#        command: >
#            sh -c "
#            sleep 15;
#            kafka-topics.sh --create --topic rents --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092;
#            sleep infinity;
#            "witam

        networks:
            - kafkanet


    kafka2:
        image: bitnami/kafka:latest
        hostname: kafka2
        container_name: kafka2
        ports:
            - "9093:9093"
            - "29093:29093"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:19093,EXTERNAL://:9093,DOCKER://:29093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            #KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

        depends_on:
            zookeeper:
                condition: service_healthy

        networks:
            - kafkanet


    kafka3:
        image: bitnami/kafka:latest
        hostname: kafka3
        container_name: kafka3
        ports:
            - "9094:9094"
            - "29094:29094"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:19094,EXTERNAL://:9094,DOCKER://:29094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094,DOCKER://host.docker.internal:29094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            #KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

        depends_on:
            zookeeper:
                condition: service_healthy

        networks:
            - kafkanet


volumes:
    redis-stack-data:
        driver: local

networks:
    mongonet: { }
    redisnet: { }
    kafkanet:
        driver: bridge