# Plik konfiguracyjny MongoDB
storage:
    dbPath: /data/db                    # Ścieżka, w której MongoDB zapisuje dane.
    engine: wiredTiger                  # Używany silnik przechowywania danych (WiredTiger).
    wiredTiger:
        engineConfig:
            cacheSizeGB: 2              # Rozmiar pamięci cache WiredTiger w GB. Określa, ile pamięci RAM jest przeznaczone na buforowanie danych.
        collectionConfig:
            blockCompressor: snappy     # Algorytm kompresji dla kolekcji - snappy (szybka kompresja zrównoważona z wydajnością).

systemLog:
    destination: syslog                 # Przekierowanie logów do systemowego rejestru (syslog).
    logAppend: true                     # Dodawanie logów na końcu istniejącego pliku zamiast jego nadpisywania.
    verbosity: 0                        # Poziom szczegółowości logów - 0 to poziom najniższy.

net:
    bindIp: 0.0.0.0                     # MongoDB nasłuchuje połączeń na wszystkich interfejsach sieciowych.
    port: 27017                         # Używany port MongoDB (domyślny to 27017).
    wireObjectCheck: true               # Weryfikacja poprawności obiektów BSON odbieranych przez serwer (zwiększa bezpieczeństwo).

replication:
    replSetName: rs0                    # Nazwa zestawu replik, wymagane dla replikacji.
    oplogSizeMB: 2048                   # Rozmiar dziennika operacji (oplog) w MB, używany do synchronizacji między węzłami.

security:
    authorization: enabled              # Włączenie autoryzacji - wymagane logowanie z uprawnieniami.
    keyFile: /etc/mongo/keyfile         # Ścieżka do pliku keyfile używanego do autoryzacji replikacji; wymaga identycznego pliku na każdym węźle.