# Plik konfiguracyjny MongoDB
storage:
    dbPath: /data/db  # Ścieżka do przechowywania danych
    engine: wiredTiger
    wiredTiger:
            engineConfig:
                cacheSizeGB: 2
            collectionConfig:
                blockCompressor: snappy


  #journal:
  #  enabled: true    # Włączenie dzienników

systemLog:
    destination: syslog
    #path: /var/log/mongodb/mongod.log  # Ścieżka do pliku logów
    logAppend: true   # Dodawanie logów zamiast nadpisywania
    verbosity: 0      # Poziom szczegółowości logów (0 - informacyjny, 1 - ostrzeżenia, 2 - błędy itp.)

net:
    bindIp: 0.0.0.0   # Akceptuj połączenia z wszystkich adresów IP
    port: 27017       # Port, na którym MongoDB nasłuchuje
    wireObjectCheck : true

replication:
    replSetName: rs0  # Nazwa zestawu replik
    oplogSizeMB: 2048

security:
    authorization: enabled  # Włączenie autoryzacji
    keyFile: /etc/mongo/keyfile  # Ścieżka do pliku klucza