datastax-java-driver {
    advanced.address-translator {
        class = NBD.CarRentalAddressTranslator
    }
}

datastax-java-driver {
    basic.request {
        consistency = QUORUM
        serial-consistency = SERIAL
    }
}